public class HelperClassTestExample {
	public integer addition(integer a, integer b,integer c)
    {
        return a + b + c;
    }
     
    public integer minus(integer a, integer b,integer c)
    {
        return (a - b)-c;
    }
     
    public integer multiply(integer a, integer b,integer c)
    {
        return (a * b)*c;
    }
        public integer mod(integer a, integer b)
    {
        return math.mod(a,b);
    }
}